2024-05-21 07:51:43,957 INFO    StreamThr :169665 [internal.py:wandb_internal():86] W&B internal server running at pid: 169665, started at: 2024-05-21 07:51:43.956866
2024-05-21 07:51:43,959 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: status
2024-05-21 07:51:43,963 INFO    WriterThread:169665 [datastore.py:open_for_write():87] open: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/run-y99702p8.wandb
2024-05-21 07:51:43,964 DEBUG   SenderThread:169665 [sender.py:send():382] send: header
2024-05-21 07:51:43,986 DEBUG   SenderThread:169665 [sender.py:send():382] send: run
2024-05-21 07:51:44,486 INFO    SenderThread:169665 [dir_watcher.py:__init__():211] watching files in: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/files
2024-05-21 07:51:44,487 INFO    SenderThread:169665 [sender.py:_start_run_threads():1136] run started: y99702p8 with start time 1716245503.957954
2024-05-21 07:51:44,492 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: check_version
2024-05-21 07:51:44,493 DEBUG   SenderThread:169665 [sender.py:send_request():409] send_request: check_version
2024-05-21 07:51:44,594 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: run_start
2024-05-21 07:51:44,605 DEBUG   HandlerThread:169665 [system_info.py:__init__():27] System info init
2024-05-21 07:51:44,605 DEBUG   HandlerThread:169665 [system_info.py:__init__():42] System info init done
2024-05-21 07:51:44,605 INFO    HandlerThread:169665 [system_monitor.py:start():194] Starting system monitor
2024-05-21 07:51:44,605 INFO    SystemMonitor:169665 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-21 07:51:44,605 INFO    HandlerThread:169665 [system_monitor.py:probe():214] Collecting system info
2024-05-21 07:51:44,606 INFO    SystemMonitor:169665 [interfaces.py:start():190] Started cpu monitoring
2024-05-21 07:51:44,607 INFO    SystemMonitor:169665 [interfaces.py:start():190] Started disk monitoring
2024-05-21 07:51:44,607 INFO    SystemMonitor:169665 [interfaces.py:start():190] Started gpu monitoring
2024-05-21 07:51:44,607 INFO    SystemMonitor:169665 [interfaces.py:start():190] Started memory monitoring
2024-05-21 07:51:44,608 INFO    SystemMonitor:169665 [interfaces.py:start():190] Started network monitoring
2024-05-21 07:51:44,619 DEBUG   HandlerThread:169665 [system_info.py:probe():151] Probing system
2024-05-21 07:51:44,626 DEBUG   HandlerThread:169665 [system_info.py:_probe_git():136] Probing git
2024-05-21 07:51:44,642 DEBUG   HandlerThread:169665 [system_info.py:_probe_git():144] Probing git done
2024-05-21 07:51:44,642 DEBUG   HandlerThread:169665 [system_info.py:probe():199] Probing system done
2024-05-21 07:51:44,642 DEBUG   HandlerThread:169665 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-35-generic-x86_64-with-glibc2.35', 'python': '3.9.18', 'heartbeatAt': '2024-05-20T22:51:44.619407', 'startedAt': '2024-05-20T22:51:43.951110', 'docker': None, 'cuda': None, 'args': ('--seed', '92', '--env_name', 'StarCraft2', '--experiment_name', 'Original_Mappo', '--group_name', 'Original_Mappo', '--use_reward_shaping', '--use_shaping_weight', '--num_gpu', '1'), 'state': 'running', 'program': '/home/uosai/Desktop/on-policy/onpolicy/scripts/train/train_smac.py', 'codePathLocal': 'train_smac.py', 'codePath': 'onpolicy/scripts/train/train_smac.py', 'git': {'remote': 'https://github.com/narame7/on-policy.git', 'commit': 'a843a882a6e81ddd9b6e30e03a1d91e4076549c9'}, 'email': 'singfor7012@gmail.com', 'root': '/home/uosai/Desktop/on-policy', 'host': 'uos-desktop', 'username': 'uosai', 'executable': '/home/uosai/Desktop/miniconda3/envs/marl/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4487.9002083333335, 'min': 2200.0, 'max': 3700.0}, 'cpu_freq_per_core': [{'current': 4497.66, 'min': 2200.0, 'max': 3700.0}, {'current': 4499.392, 'min': 2200.0, 'max': 3700.0}, {'current': 4493.761, 'min': 2200.0, 'max': 3700.0}, {'current': 4495.935, 'min': 2200.0, 'max': 3700.0}, {'current': 4498.114, 'min': 2200.0, 'max': 3700.0}, {'current': 4499.74, 'min': 2200.0, 'max': 3700.0}, {'current': 4502.315, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.66, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.64, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.657, 'min': 2200.0, 'max': 3700.0}, {'current': 4495.86, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.755, 'min': 2200.0, 'max': 3700.0}, {'current': 4499.049, 'min': 2200.0, 'max': 3700.0}, {'current': 4494.425, 'min': 2200.0, 'max': 3700.0}, {'current': 4502.595, 'min': 2200.0, 'max': 3700.0}, {'current': 4494.497, 'min': 2200.0, 'max': 3700.0}, {'current': 4501.786, 'min': 2200.0, 'max': 3700.0}, {'current': 4498.441, 'min': 2200.0, 'max': 3700.0}, {'current': 4499.236, 'min': 2200.0, 'max': 3700.0}, {'current': 4499.741, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.066, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.926, 'min': 2200.0, 'max': 3700.0}, {'current': 4493.451, 'min': 2200.0, 'max': 3700.0}, {'current': 4497.705, 'min': 2200.0, 'max': 3700.0}], 'disk': {'/': {'total': 233.17998886108398, 'used': 178.7558135986328}}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}, {'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}], 'memory': {'total': 62.70906448364258}}
2024-05-21 07:51:44,642 INFO    HandlerThread:169665 [system_monitor.py:probe():224] Finished collecting system info
2024-05-21 07:51:44,642 INFO    HandlerThread:169665 [system_monitor.py:probe():227] Publishing system info
2024-05-21 07:51:44,642 DEBUG   HandlerThread:169665 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-05-21 07:51:45,488 INFO    Thread-12 :169665 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/files/conda-environment.yaml
2024-05-21 07:51:46,367 DEBUG   HandlerThread:169665 [system_info.py:_save_conda():220] Saving conda packages done
2024-05-21 07:51:46,368 INFO    HandlerThread:169665 [system_monitor.py:probe():229] Finished publishing system info
2024-05-21 07:51:46,370 DEBUG   SenderThread:169665 [sender.py:send():382] send: files
2024-05-21 07:51:46,371 INFO    SenderThread:169665 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-05-21 07:51:46,374 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: python_packages
2024-05-21 07:51:46,375 DEBUG   SenderThread:169665 [sender.py:send_request():409] send_request: python_packages
2024-05-21 07:51:46,376 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: stop_status
2024-05-21 07:51:46,376 DEBUG   SenderThread:169665 [sender.py:send_request():409] send_request: stop_status
2024-05-21 07:51:46,418 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-21 07:51:46,487 INFO    Thread-12 :169665 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/files/conda-environment.yaml
2024-05-21 07:51:46,487 INFO    Thread-12 :169665 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/files/wandb-metadata.json
2024-05-21 07:51:46,487 INFO    Thread-12 :169665 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-y99702p8/files/requirements.txt
2024-05-21 07:51:46,699 DEBUG   SenderThread:169665 [sender.py:send():382] send: telemetry
2024-05-21 07:51:46,747 ERROR   wandb-upload_0:169665 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-21 07:51:46,747 ERROR   wandb-upload_0:169665 [internal_api.py:execute():374] {"errors":[{"message":"run StarCraft2/y99702p8 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-05-21 07:51:46,748 ERROR   Thread-11 :169665 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpzj83rkegwandb/va6mr7kf-wandb-metadata.json
Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-21 07:51:49,700 DEBUG   HandlerThread:169665 [handler.py:handle_request():146] handle_request: status_report
2024-05-21 07:51:50,595 INFO    MainThread:169665 [internal.py:handle_exit():76] Internal process exited
2024-05-21 07:51:50,611 INFO    memory    :169665 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-05-21 07:51:50,611 DEBUG   SystemMonitor:169665 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-21 07:51:50,611 DEBUG   SystemMonitor:169665 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-05-21 07:51:50,611 DEBUG   SystemMonitor:169665 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-05-21 07:51:50,612 DEBUG   SenderThread:169665 [sender.py:send():382] send: stats
