2024-05-21 07:51:43,936 INFO    StreamThr :169663 [internal.py:wandb_internal():86] W&B internal server running at pid: 169663, started at: 2024-05-21 07:51:43.936469
2024-05-21 07:51:43,938 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: status
2024-05-21 07:51:43,941 INFO    WriterThread:169663 [datastore.py:open_for_write():87] open: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/run-mp4b8qyr.wandb
2024-05-21 07:51:43,941 DEBUG   SenderThread:169663 [sender.py:send():382] send: header
2024-05-21 07:51:43,962 DEBUG   SenderThread:169663 [sender.py:send():382] send: run
2024-05-21 07:51:44,486 INFO    SenderThread:169663 [dir_watcher.py:__init__():211] watching files in: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/files
2024-05-21 07:51:44,487 INFO    SenderThread:169663 [sender.py:_start_run_threads():1136] run started: mp4b8qyr with start time 1716245503.936667
2024-05-21 07:51:44,498 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: check_version
2024-05-21 07:51:44,498 DEBUG   SenderThread:169663 [sender.py:send_request():409] send_request: check_version
2024-05-21 07:51:44,589 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: run_start
2024-05-21 07:51:44,600 DEBUG   HandlerThread:169663 [system_info.py:__init__():27] System info init
2024-05-21 07:51:44,600 DEBUG   HandlerThread:169663 [system_info.py:__init__():42] System info init done
2024-05-21 07:51:44,600 INFO    HandlerThread:169663 [system_monitor.py:start():194] Starting system monitor
2024-05-21 07:51:44,600 INFO    SystemMonitor:169663 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-21 07:51:44,601 INFO    HandlerThread:169663 [system_monitor.py:probe():214] Collecting system info
2024-05-21 07:51:44,601 INFO    SystemMonitor:169663 [interfaces.py:start():190] Started cpu monitoring
2024-05-21 07:51:44,602 INFO    SystemMonitor:169663 [interfaces.py:start():190] Started disk monitoring
2024-05-21 07:51:44,603 INFO    SystemMonitor:169663 [interfaces.py:start():190] Started gpu monitoring
2024-05-21 07:51:44,603 INFO    SystemMonitor:169663 [interfaces.py:start():190] Started memory monitoring
2024-05-21 07:51:44,603 INFO    SystemMonitor:169663 [interfaces.py:start():190] Started network monitoring
2024-05-21 07:51:44,619 DEBUG   HandlerThread:169663 [system_info.py:probe():151] Probing system
2024-05-21 07:51:44,625 DEBUG   HandlerThread:169663 [system_info.py:_probe_git():136] Probing git
2024-05-21 07:51:44,639 DEBUG   HandlerThread:169663 [system_info.py:_probe_git():144] Probing git done
2024-05-21 07:51:44,639 DEBUG   HandlerThread:169663 [system_info.py:probe():199] Probing system done
2024-05-21 07:51:44,639 DEBUG   HandlerThread:169663 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-35-generic-x86_64-with-glibc2.35', 'python': '3.9.18', 'heartbeatAt': '2024-05-20T22:51:44.619377', 'startedAt': '2024-05-20T22:51:43.931176', 'docker': None, 'cuda': None, 'args': ('--seed', '293', '--env_name', 'StarCraft2', '--experiment_name', 'Original_Mappo', '--group_name', 'Original_Mappo', '--use_reward_shaping', '--use_shaping_weight', '--num_gpu', '1'), 'state': 'running', 'program': '/home/uosai/Desktop/on-policy/onpolicy/scripts/train/train_smac.py', 'codePathLocal': 'train_smac.py', 'codePath': 'onpolicy/scripts/train/train_smac.py', 'git': {'remote': 'https://github.com/narame7/on-policy.git', 'commit': 'a843a882a6e81ddd9b6e30e03a1d91e4076549c9'}, 'email': 'singfor7012@gmail.com', 'root': '/home/uosai/Desktop/on-policy', 'host': 'uos-desktop', 'username': 'uosai', 'executable': '/home/uosai/Desktop/miniconda3/envs/marl/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4496.5086666666675, 'min': 2200.0, 'max': 3700.0}, 'cpu_freq_per_core': [{'current': 4491.554, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.515, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.483, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.409, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.335, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.547, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.172, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.552, 'min': 2200.0, 'max': 3700.0}, {'current': 4428.106, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.572, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.478, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.395, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.257, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.53, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.079, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.432, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.541, 'min': 2200.0, 'max': 3700.0}, {'current': 4490.467, 'min': 2200.0, 'max': 3700.0}, {'current': 4490.918, 'min': 2200.0, 'max': 3700.0}, {'current': 4489.991, 'min': 2200.0, 'max': 3700.0}, {'current': 4473.459, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.563, 'min': 2200.0, 'max': 3700.0}, {'current': 4490.798, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.452, 'min': 2200.0, 'max': 3700.0}], 'disk': {'/': {'total': 233.17998886108398, 'used': 178.75580978393555}}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}, {'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}], 'memory': {'total': 62.70906448364258}}
2024-05-21 07:51:44,639 INFO    HandlerThread:169663 [system_monitor.py:probe():224] Finished collecting system info
2024-05-21 07:51:44,639 INFO    HandlerThread:169663 [system_monitor.py:probe():227] Publishing system info
2024-05-21 07:51:44,639 DEBUG   HandlerThread:169663 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-05-21 07:51:45,489 INFO    Thread-12 :169663 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/files/conda-environment.yaml
2024-05-21 07:51:47,240 DEBUG   HandlerThread:169663 [system_info.py:_save_conda():220] Saving conda packages done
2024-05-21 07:51:47,241 INFO    HandlerThread:169663 [system_monitor.py:probe():229] Finished publishing system info
2024-05-21 07:51:47,243 DEBUG   SenderThread:169663 [sender.py:send():382] send: files
2024-05-21 07:51:47,243 INFO    SenderThread:169663 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-05-21 07:51:47,247 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: python_packages
2024-05-21 07:51:47,247 DEBUG   SenderThread:169663 [sender.py:send_request():409] send_request: python_packages
2024-05-21 07:51:47,247 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: stop_status
2024-05-21 07:51:47,248 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-21 07:51:47,248 DEBUG   SenderThread:169663 [sender.py:send_request():409] send_request: stop_status
2024-05-21 07:51:47,486 DEBUG   SenderThread:169663 [sender.py:send():382] send: telemetry
2024-05-21 07:51:47,487 INFO    Thread-12 :169663 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/files/conda-environment.yaml
2024-05-21 07:51:47,487 INFO    Thread-12 :169663 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/files/wandb-metadata.json
2024-05-21 07:51:47,488 INFO    Thread-12 :169663 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-mp4b8qyr/files/requirements.txt
2024-05-21 07:51:47,634 ERROR   wandb-upload_0:169663 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-21 07:51:47,634 ERROR   wandb-upload_0:169663 [internal_api.py:execute():374] {"errors":[{"message":"run StarCraft2/mp4b8qyr not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-05-21 07:51:47,634 ERROR   Thread-11 :169663 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmps_s2c27lwandb/phc759bd-wandb-metadata.json
Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-21 07:51:49,486 DEBUG   HandlerThread:169663 [handler.py:handle_request():146] handle_request: status_report
2024-05-21 07:51:50,590 INFO    MainThread:169663 [internal.py:handle_exit():76] Internal process exited
2024-05-21 07:51:50,606 INFO    cpu       :169663 [interfaces.py:monitor():140] Process cpu has exited.
2024-05-21 07:51:50,607 INFO    memory    :169663 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-05-21 07:51:50,607 DEBUG   SystemMonitor:169663 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-21 07:51:50,607 DEBUG   SystemMonitor:169663 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-05-21 07:51:50,607 DEBUG   SystemMonitor:169663 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-05-21 07:51:50,608 DEBUG   SenderThread:169663 [sender.py:send():382] send: stats
