2024-05-21 07:51:43,981 INFO    StreamThr :169678 [internal.py:wandb_internal():86] W&B internal server running at pid: 169678, started at: 2024-05-21 07:51:43.981203
2024-05-21 07:51:43,983 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: status
2024-05-21 07:51:43,987 INFO    WriterThread:169678 [datastore.py:open_for_write():87] open: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/run-99axwa3u.wandb
2024-05-21 07:51:43,988 DEBUG   SenderThread:169678 [sender.py:send():382] send: header
2024-05-21 07:51:44,007 DEBUG   SenderThread:169678 [sender.py:send():382] send: run
2024-05-21 07:51:44,511 INFO    SenderThread:169678 [dir_watcher.py:__init__():211] watching files in: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/files
2024-05-21 07:51:44,511 INFO    SenderThread:169678 [sender.py:_start_run_threads():1136] run started: 99axwa3u with start time 1716245503.981552
2024-05-21 07:51:44,519 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: check_version
2024-05-21 07:51:44,520 DEBUG   SenderThread:169678 [sender.py:send_request():409] send_request: check_version
2024-05-21 07:51:44,611 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: run_start
2024-05-21 07:51:44,621 DEBUG   HandlerThread:169678 [system_info.py:__init__():27] System info init
2024-05-21 07:51:44,621 DEBUG   HandlerThread:169678 [system_info.py:__init__():42] System info init done
2024-05-21 07:51:44,621 INFO    HandlerThread:169678 [system_monitor.py:start():194] Starting system monitor
2024-05-21 07:51:44,621 INFO    SystemMonitor:169678 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-21 07:51:44,621 INFO    HandlerThread:169678 [system_monitor.py:probe():214] Collecting system info
2024-05-21 07:51:44,622 INFO    SystemMonitor:169678 [interfaces.py:start():190] Started cpu monitoring
2024-05-21 07:51:44,623 INFO    SystemMonitor:169678 [interfaces.py:start():190] Started disk monitoring
2024-05-21 07:51:44,626 INFO    SystemMonitor:169678 [interfaces.py:start():190] Started gpu monitoring
2024-05-21 07:51:44,626 INFO    SystemMonitor:169678 [interfaces.py:start():190] Started memory monitoring
2024-05-21 07:51:44,627 INFO    SystemMonitor:169678 [interfaces.py:start():190] Started network monitoring
2024-05-21 07:51:44,638 DEBUG   HandlerThread:169678 [system_info.py:probe():151] Probing system
2024-05-21 07:51:44,646 DEBUG   HandlerThread:169678 [system_info.py:_probe_git():136] Probing git
2024-05-21 07:51:44,660 DEBUG   HandlerThread:169678 [system_info.py:_probe_git():144] Probing git done
2024-05-21 07:51:44,660 DEBUG   HandlerThread:169678 [system_info.py:probe():199] Probing system done
2024-05-21 07:51:44,660 DEBUG   HandlerThread:169678 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-35-generic-x86_64-with-glibc2.35', 'python': '3.9.18', 'heartbeatAt': '2024-05-20T22:51:44.639055', 'startedAt': '2024-05-20T22:51:43.975382', 'docker': None, 'cuda': None, 'args': ('--seed', '753', '--env_name', 'StarCraft2', '--experiment_name', 'Original_Mappo', '--group_name', 'Original_Mappo', '--use_reward_shaping', '--use_shaping_weight', '--num_gpu', '1'), 'state': 'running', 'program': '/home/uosai/Desktop/on-policy/onpolicy/scripts/train/train_smac.py', 'codePathLocal': 'train_smac.py', 'codePath': 'onpolicy/scripts/train/train_smac.py', 'git': {'remote': 'https://github.com/narame7/on-policy.git', 'commit': 'a843a882a6e81ddd9b6e30e03a1d91e4076549c9'}, 'email': 'singfor7012@gmail.com', 'root': '/home/uosai/Desktop/on-policy', 'host': 'uos-desktop', 'username': 'uosai', 'executable': '/home/uosai/Desktop/miniconda3/envs/marl/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4419.097166666667, 'min': 2200.0, 'max': 3700.0}, 'cpu_freq_per_core': [{'current': 4491.53, 'min': 2200.0, 'max': 3700.0}, {'current': 4489.215, 'min': 2200.0, 'max': 3700.0}, {'current': 4489.385, 'min': 2200.0, 'max': 3700.0}, {'current': 4488.571, 'min': 2200.0, 'max': 3700.0}, {'current': 4367.087, 'min': 2200.0, 'max': 3700.0}, {'current': 4490.982, 'min': 2200.0, 'max': 3700.0}, {'current': 3590.567, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.564, 'min': 2200.0, 'max': 3700.0}, {'current': 4479.516, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.553, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.474, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.978, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.381, 'min': 2200.0, 'max': 3700.0}, {'current': 4241.238, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.55, 'min': 2200.0, 'max': 3700.0}, {'current': 3719.829, 'min': 2200.0, 'max': 3700.0}, {'current': 4489.817, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.461, 'min': 2200.0, 'max': 3700.0}, {'current': 3591.9, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.562, 'min': 2200.0, 'max': 3700.0}, {'current': 4134.877, 'min': 2200.0, 'max': 3700.0}, {'current': 4488.019, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.396, 'min': 2200.0, 'max': 3700.0}, {'current': 4491.559, 'min': 2200.0, 'max': 3700.0}], 'disk': {'/': {'total': 233.17998886108398, 'used': 178.7558135986328}}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}, {'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}], 'memory': {'total': 62.70906448364258}}
2024-05-21 07:51:44,660 INFO    HandlerThread:169678 [system_monitor.py:probe():224] Finished collecting system info
2024-05-21 07:51:44,660 INFO    HandlerThread:169678 [system_monitor.py:probe():227] Publishing system info
2024-05-21 07:51:44,660 DEBUG   HandlerThread:169678 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-05-21 07:51:45,513 INFO    Thread-12 :169678 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/files/conda-environment.yaml
2024-05-21 07:51:46,356 DEBUG   HandlerThread:169678 [system_info.py:_save_conda():220] Saving conda packages done
2024-05-21 07:51:46,357 INFO    HandlerThread:169678 [system_monitor.py:probe():229] Finished publishing system info
2024-05-21 07:51:46,360 DEBUG   SenderThread:169678 [sender.py:send():382] send: files
2024-05-21 07:51:46,360 INFO    SenderThread:169678 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-05-21 07:51:46,366 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: python_packages
2024-05-21 07:51:46,366 DEBUG   SenderThread:169678 [sender.py:send_request():409] send_request: python_packages
2024-05-21 07:51:46,367 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: stop_status
2024-05-21 07:51:46,367 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-21 07:51:46,368 DEBUG   SenderThread:169678 [sender.py:send_request():409] send_request: stop_status
2024-05-21 07:51:46,512 INFO    Thread-12 :169678 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/files/conda-environment.yaml
2024-05-21 07:51:46,512 INFO    Thread-12 :169678 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/files/wandb-metadata.json
2024-05-21 07:51:46,513 INFO    Thread-12 :169678 [dir_watcher.py:_on_file_created():271] file/dir created: /home/uosai/Desktop/on-policy/onpolicy/scripts/results/StarCraft2/3m/rmappo/Original_Mappo/wandb/run-20240521_075143-99axwa3u/files/requirements.txt
2024-05-21 07:51:46,698 DEBUG   SenderThread:169678 [sender.py:send():382] send: telemetry
2024-05-21 07:51:46,744 ERROR   wandb-upload_0:169678 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-05-21 07:51:46,744 ERROR   wandb-upload_0:169678 [internal_api.py:execute():374] {"errors":[{"message":"run StarCraft2/99axwa3u not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-05-21 07:51:46,745 ERROR   Thread-11 :169678 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp2qqfndr6wandb/u1r41k8t-wandb-metadata.json
Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/uosai/Desktop/miniconda3/envs/marl/lib/python3.9/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-21 07:51:49,699 DEBUG   HandlerThread:169678 [handler.py:handle_request():146] handle_request: status_report
2024-05-21 07:51:50,612 INFO    MainThread:169678 [internal.py:handle_exit():76] Internal process exited
2024-05-21 07:51:50,625 INFO    cpu       :169678 [interfaces.py:monitor():140] Process cpu has exited.
2024-05-21 07:51:50,625 DEBUG   SystemMonitor:169678 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-21 07:51:50,626 DEBUG   SystemMonitor:169678 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-05-21 07:51:50,626 DEBUG   SystemMonitor:169678 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-05-21 07:51:50,627 DEBUG   SenderThread:169678 [sender.py:send():382] send: stats
